#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
import sys
import uuid
from datetime import datetime, timezone
from email import policy
from email.parser import BytesParser
from email.utils import getaddresses, parseaddr
from pathlib import Path


ARCHIVE_DIR = Path("/srv/mailin/archive/facebook-approval")
STATE_DIR = Path("/srv/mailin/archive/facebook-approval-state")
JOB_DIR = Path("/srv/mailin/archive/facebook-approval-jobs/pending")
TOKEN_RE = re.compile(r"APPROVE-FACEBOOK-POST\s*:\s*([A-Za-z0-9]{20,80})", re.IGNORECASE)


def unique_prefix() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "-" + uuid.uuid4().hex[:8]


def message_text(message) -> str:
    parts: list[str] = []
    if message.is_multipart():
        for part in message.walk():
            if part.get_content_maintype() == "multipart":
                continue
            disposition = (part.get_content_disposition() or "").lower()
            if disposition == "attachment":
                continue
            content_type = part.get_content_type().lower()
            if content_type not in {"text/plain", "text/html"}:
                continue
            try:
                parts.append(part.get_content())
            except Exception:
                payload = part.get_payload(decode=True)
                if payload:
                    parts.append(payload.decode(part.get_content_charset() or "utf-8", errors="replace"))
    else:
        try:
            parts.append(message.get_content())
        except Exception:
            payload = message.get_payload(decode=True)
            if payload:
                parts.append(payload.decode(message.get_content_charset() or "utf-8", errors="replace"))
    return "\n".join(parts)


def sender_label(message) -> str:
    addresses = getaddresses(message.get_all("From", []))
    if not addresses:
        return "mail-reply"
    _, address = addresses[0]
    address = address.strip().lower()
    if not address:
        return "mail-reply"
    return "mail-reply:" + re.sub(r"[^a-z0-9@._+-]+", "_", address)[:120]


def should_ignore_autogenerated(message) -> str | None:
    auto_submitted = (message.get("Auto-Submitted") or "").strip().lower()
    if auto_submitted and auto_submitted != "no":
        return "auto-submitted"
    precedence = (message.get("Precedence") or "").strip().lower()
    if precedence in {"bulk", "junk", "list"}:
        return "precedence-" + precedence
    from_addr = parseaddr(message.get("From") or "")[1].lower()
    if from_addr.startswith("mailer-daemon@") or from_addr.startswith("postmaster@"):
        return "bounce-sender"
    return None


def state_path(token: str) -> Path:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    return STATE_DIR / (token.lower() + ".json")


def claim_token(token: str, meta: dict) -> bool:
    path = state_path(token)
    if path.exists():
        return False
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    tmp.rename(path)
    return True


def update_token_state(token: str, meta: dict) -> None:
    path = state_path(token)
    path.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")


def write_job(token: str, meta: dict) -> Path:
    JOB_DIR.mkdir(parents=True, exist_ok=True)
    path = JOB_DIR / (token.lower() + ".json")
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    tmp.rename(path)
    return path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--recipient", required=True)
    parser.add_argument("--original-recipient", default="")
    parser.add_argument("--sender", default="")
    args = parser.parse_args()

    message_bytes = sys.stdin.buffer.read()
    message = BytesParser(policy=policy.default).parsebytes(message_bytes)
    prefix = unique_prefix()
    ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
    raw_path = ARCHIVE_DIR / f"{prefix}.eml"
    raw_path.write_bytes(message_bytes)

    ignored_reason = should_ignore_autogenerated(message)
    if ignored_reason:
        print(f"facebook-approval-router ignored={ignored_reason} raw={raw_path}", flush=True)
        return 0

    text = message_text(message)
    match = TOKEN_RE.search(text)
    if not match:
        print(f"facebook-approval-router token=missing raw={raw_path}", flush=True)
        return 0

    token = match.group(1).lower()
    source = sender_label(message)
    meta = {
        "token": token,
        "source": source,
        "recipient": args.recipient,
        "original_recipient": args.original_recipient,
        "sender": args.sender,
        "raw": str(raw_path),
        "received_at": datetime.now(timezone.utc).isoformat(),
        "status": "queued",
    }
    if not claim_token(token, meta):
        print(f"facebook-approval-router token={token} status=duplicate raw={raw_path}", flush=True)
        return 0

    job_path = write_job(token, meta)
    meta["job"] = str(job_path)
    update_token_state(token, meta)
    print(f"facebook-approval-router token={token} status=queued job={job_path} raw={raw_path}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
